package util;

public enum ModelType {
    NORMAL,
    WITH_NORMAL_MAP,
    INSTANCED,
    INSTANCED_WITH_NORMAL_MAP,
    ANIMATED,
    ANIMATED_INSTANCED,
    ANIMATED_WITH_NORMAL_MAP,
    ANIMATED_INSTANCED_WITH_NORMAL_MAP,
}
